### ISSUE TITLE
Path to procfs is not configurable

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-meminfo#11]
The path to procfs is currently [hardcoded](https://github.com/intelsdi-x/snap-plugin-collector-meminfo/blob/22c900bb6883de3255f37ef9adb6a0c24d470f04/mem/mem.go#L46) to /proc. This makes it hard (if even possible) to use the plugin when snapd is run in a Docker container.

**Comment by marcin-krolik** [comment]
Fixed with #12 
- procfs/meminfo path is configurable via task manifest
- defaults to /proc/meminfo
- static construction of metric catalog
- updated tests and dependencies

cc @elemoine @obourdon
